const { Client } = require('pg');

const client = new Client({
  connectionString: 'postgresql://postgres:NexusFinance2026@db.pmunovzqcarjtunjrljq.supabase.co:5432/postgres',
  ssl: { rejectUnauthorized: false }
});

const sql = `
-- Table: public.usuarios (Profiles)
CREATE TABLE IF NOT EXISTS public.usuarios (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  role TEXT DEFAULT 'ADMIN' CHECK (role IN ('ADMIN', 'GERENTE', 'OPERADOR')),
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own profile" ON public.usuarios;
CREATE POLICY "Users can view own profile" ON public.usuarios FOR SELECT USING (id = auth.uid());
DROP POLICY IF EXISTS "Users can update own profile" ON public.usuarios;
CREATE POLICY "Users can update own profile" ON public.usuarios FOR UPDATE USING (id = auth.uid());
DROP POLICY IF EXISTS "Users can insert own profile" ON public.usuarios;
CREATE POLICY "Users can insert own profile" ON public.usuarios FOR INSERT WITH CHECK (id = auth.uid());

CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.usuarios (id, nome, email, role)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'nome', split_part(new.email, '@', 1)), 
    new.email, 
    'ADMIN'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Table: produtos
CREATE TABLE IF NOT EXISTS public.produtos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  codigo_sku TEXT NOT NULL,
  categoria TEXT NOT NULL,
  preco_venda NUMERIC NOT NULL CHECK(preco_venda >= 0),
  custo_unitario NUMERIC NOT NULL CHECK(custo_unitario >= 0),
  estoque_atual NUMERIC DEFAULT 0,
  estoque_minimo NUMERIC DEFAULT 0,
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Isolate produtos" ON public.produtos;
CREATE POLICY "Isolate produtos" ON public.produtos FOR ALL USING (usuario_id = auth.uid());

-- Table: clientes
CREATE TABLE IF NOT EXISTS public.clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  tipo TEXT NOT NULL CHECK(tipo IN ('PF', 'PJ')),
  documento TEXT,
  email TEXT,
  telefone TEXT,
  segmento TEXT,
  tipo_contato TEXT DEFAULT 'Cliente',
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Isolate clientes" ON public.clientes;
CREATE POLICY "Isolate clientes" ON public.clientes FOR ALL USING (usuario_id = auth.uid());

-- Table: transacoes
CREATE TABLE IF NOT EXISTS public.transacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  data_transacao DATE NOT NULL,
  tipo TEXT NOT NULL CHECK(tipo IN ('RECEITA', 'DESPESA')),
  valor NUMERIC NOT NULL CHECK(valor >= 0),
  categoria TEXT,
  produto_id BIGINT REFERENCES public.produtos(id) ON DELETE SET NULL,
  cliente_id BIGINT REFERENCES public.clientes(id) ON DELETE SET NULL,
  status_pagamento TEXT NOT NULL DEFAULT 'PENDENTE' CHECK(status_pagamento IN ('PAGO', 'PENDENTE', 'CANCELADO')),
  forma_pagamento TEXT NOT NULL,
  descricao TEXT,
  centro_custo TEXT,
  quantidade NUMERIC,
  data_vencimento DATE,
  tags TEXT,
  is_geral BOOLEAN DEFAULT false,
  telefone_contato TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.transacoes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Isolate transacoes" ON public.transacoes;
CREATE POLICY "Isolate transacoes" ON public.transacoes FOR ALL USING (usuario_id = auth.uid());

-- Table: patrimonio
CREATE TABLE IF NOT EXISTS public.patrimonio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL,
  descricao TEXT NOT NULL,
  valor NUMERIC NOT NULL,
  data_registro DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.patrimonio ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Isolate patrimonio" ON public.patrimonio;
CREATE POLICY "Isolate patrimonio" ON public.patrimonio FOR ALL USING (usuario_id = auth.uid());

-- Table: producao
CREATE TABLE IF NOT EXISTS public.producao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  data DATE NOT NULL,
  produto_id BIGINT REFERENCES public.produtos(id) ON DELETE CASCADE,
  quantidade NUMERIC NOT NULL,
  unidade_medida TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.producao ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Isolate producao" ON public.producao;
CREATE POLICY "Isolate producao" ON public.producao FOR ALL USING (usuario_id = auth.uid());

-- Table: funcionarios
CREATE TABLE IF NOT EXISTS public.funcionarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  cargo TEXT,
  setor TEXT,
  horario_trabalho TEXT,
  data_admissao DATE,
  salario_base NUMERIC DEFAULT 0,
  encargos_beneficios NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Ativo',
  is_geral BOOLEAN DEFAULT true,
  produto_id BIGINT REFERENCES public.produtos(id) ON DELETE SET NULL,
  valor_diaria NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.funcionarios ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Isolate funcionarios" ON public.funcionarios;
CREATE POLICY "Isolate funcionarios" ON public.funcionarios FOR ALL USING (usuario_id = auth.uid());

-- Table: apontamentos
CREATE TABLE IF NOT EXISTS public.apontamentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  funcionario_id BIGINT NOT NULL REFERENCES public.funcionarios(id) ON DELETE CASCADE,
  data DATE NOT NULL,
  status TEXT NOT NULL,
  valor_diaria_pago NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.apontamentos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Isolate apontamentos" ON public.apontamentos;
CREATE POLICY "Isolate apontamentos" ON public.apontamentos FOR ALL USING (usuario_id = auth.uid());
`;

async function migrate() {
  try {
    await client.connect();
    console.log('Connected to Supabase PostgreSQL');
    await client.query(sql);
    console.log('Migration applied successfully');
  } catch (err) {
    console.error('Migration failed:', err);
  } finally {
    await client.end();
  }
}

migrate();
